export const countryFlags: Record<string, string> = {
  Alemanha: "/flags/germany.svg",
  Áustria: "/flags/austria.svg",
  Bélgica: "/flags/belgium.svg",
  Brasil: "/flags/brazil.svg",
  Chipre: "/flags/cyprus.svg",
  Espanha: "/flags/spain.svg",
  Escócia: "/flags/scotland.svg",
  França: "/flags/france.svg",
  Hungria: "/flags/hungary.svg",
  Inglaterra: "/flags/england.svg",
  Irlanda: "/flags/ireland.svg",
  Israel: "/flags/israel.svg",
  Itália: "/flags/italy.svg",
  Palestina: "/flags/palestine.svg",
  Polônia: "/flags/poland.svg",
  Portugal: "/flags/portugal.svg",
  "País de Gales": "/flags/wales.svg",
  "Países Baixos": "/flags/netherlands.svg",
  "Reino Unido": "/flags/united-kingdom.svg",
  Turquia: "/flags/turkey.svg",
};
